In [1]:
import numpy as np

In [2]:
arr = np.array([
    [10,20,30,40],
    [50,60,70,80],
    [90,100,110,120]
])
print(" given array ")
print(arr)
print()

 given array 
[[ 10  20  30  40]
 [ 50  60  70  80]
 [ 90 100 110 120]]



In [3]:
#a Extrat the seconf row
second_row = arr[1]
print("second row")
print(second_row)
print()

second row
[50 60 70 80]



In [4]:
#b Extract the first two rows and the second twe colums
part = arr[:2,2:]
print("first two row, second two coloum")
print(part)
print()

first two row, second two coloum
[[30 40]
 [70 80]]



In [6]:
#c Extract last colum using silicing
last_col=arr[:,-1]
print(" the last colum")
print(last_col)
print()

 the last colum
[ 40  80 120]



In [7]:
#d replace the middle row with [1,2,3,4]
arr[1]=[1,2,3,4]
print("after replacing the row one")
print(arr)
print()

after replacing the row one
[[ 10  20  30  40]
 [  1   2   3   4]
 [ 90 100 110 120]]

