In [1]:
import numpy as np

In [2]:
#a create a 3x3 matrix
A = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
print ("original Matrix A :")
print(A)
print()

original Matrix A :
[[1 2 3]
 [4 5 6]
 [7 8 9]]



In [3]:
# add 10 (scaler broadcasting)
print(" after adding 10")
print(A+10)
print()

 after adding 10
[[11 12 13]
 [14 15 16]
 [17 18 19]]



In [4]:
# add a row vector
row_vec = np.array([10,20,30])
print("after adding row vector ")
print(A + row_vec)
print()

after adding row vector 
[[11 22 33]
 [14 25 36]
 [17 28 39]]



In [5]:
# add a column vector
col_vec= np.array([
    [1],
    [2],
    [3]
])
print("after adding a column vector")
print(A+ col_vec)
print()

after adding a column vector
[[ 2  3  4]
 [ 6  7  8]
 [10 11 12]]

