In [2]:
import numpy as np

In [4]:
#create array  from 1 to 12
a = np.arange(1,13)
print("a (1.....12) :",a)

a (1.....12) : [ 1  2  3  4  5  6  7  8  9 10 11 12]


In [6]:
# reshape into 3x4
b=a.reshape(3,4)
print("\n (3,4):\n",b)


 (3,4):
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [7]:
#reshape it into 2x6
c = b.reshape(2,6)
print("\n (2,6):\n",c)


 (2,6):
 [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [9]:
#task 2 flatten() , ravel() , on 2D array c
f_copy = c.flatten()
f_view = c.ravel()

print("\n f_copy ( form c.flatten()):", f_copy)
print ("\n f_copy (from c.ravel()):", f_view)


 f_copy ( form c.flatten()): [ 1  2  3  4  5  6  7  8  9 10 11 12]

 f_copy (from c.ravel()): [ 1  2  3  4  5  6  7  8  9 10 11 12]


In [12]:
# modify 
f_view[0]= 44
print("\n After f_view[0] = 44")
print("f_view:",f_view)
print("  c now become :\n",c)


 After f_view[0] = 44
f_view: [44  2  3  4  5  6  7  8  9 10 11 12]
  c now become :
 [[44  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [14]:
# Given arr = np.arange(1,10).reshape(3,3)
arr = np.arange(1,10).reshape(3,3)
print("\n arr:\n",arr)


 arr:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [17]:
arr_f = arr.flatten()
arr_rav= arr.ravel()

print("\n arr_f :",arr_f)
print("\n arr_rav :",arr_rav)


 arr_f : [1 2 3 4 5 6 7 8 9]

 arr_rav : [1 2 3 4 5 6 7 8 9]


In [18]:
# change arr_f 
arr_f[0] = -44
print("\n After arr_f[0] = -44")
print("arr_flat", arr_f)
print(" arr now:\n",arr)


 After arr_f[0] = -44
arr_flat [-44   2   3   4   5   6   7   8   9]
 arr now:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [19]:
# change arr_rav 
arr_rav[0] = -44
print("\n After arr_rav[0] = -44")
print("arr_rav:", arr_rav)
print(" now arr:\n", arr)


 After arr_rav[0] = -44
arr_rav: [-44   2   3   4   5   6   7   8   9]
 now arr:
 [[-44   2   3]
 [  4   5   6]
 [  7   8   9]]
