In [2]:
import numpy as np

In [3]:
zero_matrix=np.zeros((4,4))
print("zero matrix of 4*4:")
print(zero_matrix)

zero matrix of 4*4:
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [7]:
# b one matrix of size 3x2
one_matrix = np.ones((3,2))
print("one matrix 3x2")
print(one_matrix)
print()

one matrix 3x2
[[1. 1.]
 [1. 1.]
 [1. 1.]]



In [8]:
#c constant value array
const_matrix = np.full((5,5),7)
print("constand matrix of 5x5 with 7 value")
print(const_matrix)
print()

constand matrix of 5x5 with 7 value
[[7 7 7 7 7]
 [7 7 7 7 7]
 [7 7 7 7 7]
 [7 7 7 7 7]
 [7 7 7 7 7]]



In [12]:
#d random interger array 3x4 with values between 10 and 99
random_matrix = np.random.randint(10,100, size=(3,4))
print("random interger array ")
print(random_matrix)
print()
                                  

random interger array 
[[66 49 70 23]
 [66 28 66 37]
 [25 17 95 24]]



In [13]:
#e array using arange from 5 to 50 with step 5 ,reshaped 3x3
arr=np.arange(5,50,5).reshape(3,3)
print("array using arange , with reshaped of 3x3")
print(arr)

array using arange , with reshaped of 3x3
[[ 5 10 15]
 [20 25 30]
 [35 40 45]]
