In [1]:
import numpy as np

In [2]:
#1D array
arr1 = np.arange(1,11)
print(" 1D array :",arr1)

 1D array : [ 1  2  3  4  5  6  7  8  9 10]


In [4]:
#2D array
arr2 = np.arange(1,10).reshape(3,3)
print("2d array \n",arr2)

2d array 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [10]:
#Display 
for arr in [arr1,arr2]:
    print("Array \n",arr)
    print("Dimenssion \n",arr.ndim)
    print("Size \n",arr.size)
    print("Shape \n", arr.shape)
    print("Data types \n", arr.dtype)
    print("Item size \n",arr.itemsize)

Array 
 [ 1  2  3  4  5  6  7  8  9 10]
Dimenssion 
 1
Size 
 10
Shape 
 (10,)
Data types 
 int32
Item size 
 4
Array 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Dimenssion 
 2
Size 
 9
Shape 
 (3, 3)
Data types 
 int32
Item size 
 4


In [13]:
#3x3 float to integer 
arr3 = np.array([
    [1.1,2.2,3.3],
    [4.4,5.5,6.6],
    [7.7,8.8,9.9]
])
print("arr3 \n",arr3)

int_result= arr3.astype(int)
print("converted arr3 \n",int_result)



arr3 
 [[1.1 2.2 3.3]
 [4.4 5.5 6.6]
 [7.7 8.8 9.9]]
converted arr3 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
